export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = " LOGIN_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = " LOAD_USER_FAIL";

export const LOGOUT = "LOGOUT";

export const ADDPOST_SUCCESS = "ADDPOST_SUCCESS";
export const ADDPOST_FAIL = "ADDPOST_FAIL";

export const GETPOSTS = "GETPOSTS";
export const GET_POST = "GET_POST";
export const GETBYDATE = "GETBYDATE";

export const AADCOMMENT_SUCCESS = "AADCOMMENT_SUCCESS";
export const AADCOOMENT_FAIL = "AADCOOMENT_FAIL";

export const AADLIKE_SUCCESS = "AADLIKE_SUCCESS";
export const AADLIKE_FAIL = "AADLIKE_FAIL";

export const MOST_LIKED_POST = "MOST_LIKED_POST";
export const LIKEPOST_ERROR = "LIKEPOST_ERROR";
